# Generated by Django 2.1.7 on 2019-03-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opiniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opiniao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parceiras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parceira', models.TextField()),
                ('formacao', models.CharField(max_length=60)),
                ('profissao', models.CharField(max_length=60)),
                ('endereco_atend', models.CharField(max_length=100)),
                ('tipo_atend', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=10)),
                ('telefone_parceiras', models.CharField(max_length=11)),
                ('celular_parceiras', models.CharField(max_length=11)),
                ('email_parceiras', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.TextField()),
                ('dt_nasc_usuario', models.DateField()),
                ('email_usuario', models.EmailField(max_length=30)),
                ('senha_usuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField(default=0)),
            ],
        ),
    ]
