# Generated by Django 2.1.7 on 2019-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0003_tipoatendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento', models.CharField(max_length=200)),
                ('endereco_estabelecimento', models.CharField(max_length=200)),
                ('horario_estabelecimento', models.CharField(max_length=200)),
            ],
        ),
    ]
