# Generated by Django 2.1.7 on 2019-03-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0004_estabelecimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={'verbose_name_plural': 'Estabelecimento'},
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='telefone_estabelecimento',
            field=models.CharField(default='SOME STRING', max_length=11),
        ),
    ]
