# Generated by Django 2.1.7 on 2019-03-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0005_auto_20190317_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='telefone_estabelecimento',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parceiras',
            name='celular_parceiras',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parceiras',
            name='telefone_parceiras',
            field=models.CharField(max_length=20),
        ),
    ]
