# Generated by Django 2.1.7 on 2019-03-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0006_auto_20190317_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovelace.Estabelecimento')),
            ],
        ),
    ]
