# Generated by Django 2.1.7 on 2019-03-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0007_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
    ]
