# Generated by Django 2.1.7 on 2019-03-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0008_categoria_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categoria'},
        ),
    ]
