# Generated by Django 2.1.7 on 2019-03-18 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelace', '0009_auto_20190317_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroParceiras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('parceiras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovelace.Parceiras')),
            ],
            options={
                'verbose_name_plural': 'FiltroParceiras',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dt_nasc_usuario',
            field=models.DateTimeField(default='DD/MM/AAAA', verbose_name='Data de Nascimento'),
        ),
    ]
